# Generated by Django 3.2.7 on 2021-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_num',
            field=models.CharField(blank=True, default=' ', max_length=6, unique=True),
        ),
    ]
