# Generated by Django 3.2.7 on 2021-12-06 16:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_zone_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_num',
            field=models.CharField(default=api.models.get_random_code, max_length=6, unique=True),
        ),
    ]
