# Generated by Django 3.2.7 on 2021-12-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211206_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='votes_to_skip',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
